version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'db_password'
    networks:
      - my_net
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - my_net
  
networks:
    my_net: