version: '3'
services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/usr/src/app
    depends_on:
      - backend
    env_file:
      - ./Frontend/.env.local
    networks:
      - my_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "1337:1337"
      - "3030:3030"
      - "1339:1339"
      - "1340:1340"
      - "1341:1341"
      - "1342:1342"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src/app
    networks:
      - my_net

  db:
    image: postgres
    restart: always
    volumes:
      - postgressdb:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - my_net
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - my_net
  


volumes:
  postgressdb:
networks:
    my_net:
