export {default as ProfileInfoNav} from './components/ProfileInfoNav'
export {default as ProfileInfo} from './components/ProfileInfo'
export {default as ProfileAvatar} from './components/ProfileAvatar'
export {default as History} from './components/History'
export {default as Groups} from './components/Groups'
export {default as Friends} from './components/Friends'
export {default as Achievevements} from './components/Achievevements'